### ISSUE TITLE
Setup.py is broken

### ISSUE THREAD

**Issue by ghulands** [chaddotson/py-radar#3]
the mode for reading the requirements.txt in setup.py is wrong.

ValueError: invalid mode: 'r''

This is preventing pip install from working

**Comment by chaddotson** [comment]
Whoops.  Fixed  I was working on updating to py3 a few weeks back and broke it.  Nice catch.

**Comment by chaddotson** [comment]
I think the api for their radar imagery has been deprecated.  The package currently gets 404s and they have a completely new radar site.
