### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by hallyn** [chaddotson/py-radar#4]
Hi - any updated info?  Sure seems to have stopped working :(  Have you heard any word that the old API might come back online?

(Thanks in any case, this project was very useful)

**Comment by chaddotson** [comment]
I've been searching off and on but it seems that since they upgraded their radar feature, the imagery is no longer available via api.  I was working on finally upgrading this project to python3 when the api went offline.

**Comment by hallyn** [comment]
Thanks for the update.
